export const listWeeks = [
  {
    id: 1,
    name: 'Semana 1 Embarazo',
    slug: 'semana-1-embarazo',
    week: '1',
    description: '',
    permalink: '/semana-1-embarazo/',
    link: 'https://eresmama.com/semana-1-del-embarazo/',
  },
  {
    id: 2,
    name: 'Semana 2 Embarazo',
    slug: 'semana-2-embarazo',
    week: '2',
    description: '',
    permalink: '/semana-2-embarazo/',
    link: 'https://eresmama.com/semana-2-del-embarazo/',
  },
  {
    id: 3,
    name: 'Semana 3 Embarazo',
    slug: 'semana-3-embarazo',
    week: '3',
    description: '',
    permalink: '/semana-3-embarazo/',
    link: 'https://eresmama.com/semana-3-del-embarazo/',
  },
  {
    id: 4,
    name: 'Semana 4 Embarazo',
    slug: 'semana-4-embarazo',
    week: '4',
    description: '',
    permalink: '/semana-4-embarazo/',
    link: 'https://eresmama.com/semana-4-del-embarazo/',
  },
  {
    id: 5,
    name: 'Semana 5 Embarazo',
    slug: 'semana-5-embarazo',
    week: '5',
    description: '',
    permalink: '/semana-5-embarazo/',
    link: 'https://eresmama.com/semana-5-del-embarazo/',
  },
  {
    id: 6,
    name: 'Semana 6 Embarazo',
    slug: 'semana-6-embarazo',
    week: '6',
    description: '',
    permalink: '/semana-6-embarazo/',
    link: 'https://eresmama.com/semana-6-del-embarazo/',
  },
  {
    id: 7,
    name: 'Semana 7 Embarazo',
    slug: 'semana-7-embarazo',
    week: '7',
    description: '',
    permalink: '/semana-7-embarazo/',
    link: 'https://eresmama.com/semana-7-del-embarazo/',
  },
  {
    id: 8,
    name: 'Semana 8 Embarazo',
    slug: 'semana-8-embarazo',
    week: '8',
    description: '',
    permalink: '/semana-8-embarazo/',
    link: 'https://eresmama.com/semana-8-del-embarazo/',
  },
  {
    id: 9,
    name: 'Semana 9 Embarazo',
    slug: 'semana-9-embarazo',
    week: '9',
    description: '',
    permalink: '/semana-9-embarazo/',
    link: 'https://eresmama.com/semana-9-del-embarazo/',
  },
  {
    id: 10,
    name: 'Semana 10 Embarazo',
    slug: 'semana-10-embarazo',
    week: '3',
    description: '',
    permalink: '/semana-10-embarazo/',
    link: 'https://eresmama.com/semana-10-del-embarazo/',
  },
  {
    id: 11,
    name: 'Semana 11 Embarazo',
    slug: 'semana-11-embarazo',
    week: '11',
    description: '',
    permalink: '/semana-11-embarazo/',
    link: 'https://eresmama.com/semana-11-del-embarazo/',
  },
  {
    id: 12,
    name: 'Semana 12 Embarazo',
    slug: 'semana-12-embarazo',
    week: '12',
    description: '',
    permalink: '/semana-12-embarazo/',
    link: 'https://eresmama.com/semana-12-del-embarazo/',
  },
  {
    id: 13,
    name: 'Semana 13 Embarazo',
    slug: 'semana-13-embarazo',
    week: '13',
    description: '',
    permalink: '/semana-13-embarazo/',
    link: 'https://eresmama.com/semana-13-del-embarazo/',
  },
  {
    id: 14,
    name: 'Semana 14 Embarazo',
    slug: 'semana-14-embarazo',
    week: '14',
    description: '',
    permalink: '/semana-14-embarazo/',
    link: 'https://eresmama.com/semana-14-del-embarazo/',
  },
  {
    id: 15,
    name: 'Semana 15 Embarazo',
    slug: 'semana-15-embarazo',
    week: '15',
    description: '',
    permalink: '/semana-15-embarazo/',
    link: 'https://eresmama.com/semana-15-del-embarazo/',
  },
  {
    id: 16,
    name: 'Semana 16 Embarazo',
    slug: 'semana-16-embarazo',
    week: '16',
    description: '',
    permalink: '/semana-16-embarazo/',
    link: 'https://eresmama.com/semana-16-del-embarazo/',
  },
  {
    id: 17,
    name: 'Semana 17 Embarazo',
    slug: 'semana-17-embarazo',
    week: '17',
    description: '',
    permalink: '/semana-17-embarazo/',
    link: 'https://eresmama.com/semana-17-del-embarazo/',
  },
  {
    id: 18,
    name: 'Semana 18 Embarazo',
    slug: 'semana-18-embarazo',
    week: '18',
    description: '',
    permalink: '/semana-18-embarazo/',
    link: 'https://eresmama.com/semana-18-del-embarazo/',
  },
  {
    id: 19,
    name: 'Semana 19 Embarazo',
    slug: 'semana-19-embarazo',
    week: '19',
    description: '',
    permalink: '/semana-19-embarazo/',
    link: 'https://eresmama.com/semana-19-del-embarazo/',
  },
  {
    id: 20,
    name: 'Semana 20 Embarazo',
    slug: 'semana-20-embarazo',
    week: '20',
    description: '',
    permalink: '/semana-20-embarazo/',
    link: 'https://eresmama.com/semana-20-del-embarazo/',
  },
  {
    id: 21,
    name: 'Semana 21 Embarazo',
    slug: 'semana-21-embarazo',
    week: '21',
    description: '',
    permalink: '/semana-21-embarazo/',
    link: 'https://eresmama.com/semana-21-del-embarazo/',
  },
  {
    id: 22,
    name: 'Semana 22 Embarazo',
    slug: 'semana-22-embarazo',
    week: '22',
    description: '',
    permalink: '/semana-22-embarazo/',
    link: 'https://eresmama.com/semana-22-del-embarazo/',
  },
  {
    id: 23,
    name: 'Semana 23 Embarazo',
    slug: 'semana-23-embarazo',
    week: '23',
    description: '',
    permalink: '/semana-23-embarazo/',
    link: 'https://eresmama.com/semana-23-del-embarazo/',
  },
  {
    id: 24,
    name: 'Semana 24 Embarazo',
    slug: 'semana-24-embarazo',
    week: '24',
    description: '',
    permalink: '/semana-24-embarazo/',
    link: 'https://eresmama.com/semana-24-del-embarazo/',
  },
  {
    id: 25,
    name: 'Semana 25 Embarazo',
    slug: 'semana-25-embarazo',
    week: '25',
    description: '',
    permalink: '/semana-25-embarazo/',
    link: 'https://eresmama.com/semana-25-del-embarazo/',
  },
  {
    id: 26,
    name: 'Semana 26 Embarazo',
    slug: 'semana-26-embarazo',
    week: '26',
    description: '',
    permalink: '/semana-26-embarazo/',
    link: 'https://eresmama.com/semana-26-del-embarazo/',
  },
  {
    id: 27,
    name: 'Semana 27 Embarazo',
    slug: 'semana-27-embarazo',
    week: '27',
    description: '',
    permalink: '/semana-27-embarazo/',
    link: 'https://eresmama.com/semana-27-del-embarazo/',
  },
  {
    id: 28,
    name: 'Semana 28 Embarazo',
    slug: 'semana-28-embarazo',
    week: '28',
    description: '',
    permalink: '/semana-28-embarazo/',
    link: 'https://eresmama.com/semana-28-del-embarazo/',
  },
  {
    id: 29,
    name: 'Semana 29 Embarazo',
    slug: 'semana-29-embarazo',
    week: '29',
    description: '',
    permalink: '/semana-29-embarazo/',
    link: 'https://eresmama.com/semana-29-del-embarazo/',
  },
  {
    id: 30,
    name: 'Semana 30 Embarazo',
    slug: 'semana-30-embarazo',
    week: '30',
    description: '',
    permalink: '/semana-30-embarazo/',
    link: 'https://eresmama.com/semana-30-del-embarazo/',
  },
  {
    id: 31,
    name: 'Semana 31 Embarazo',
    slug: 'semana-31-embarazo',
    week: '31',
    description: '',
    permalink: '/semana-31-embarazo/',
    link: 'https://eresmama.com/semana-31-del-embarazo/',
  },
  {
    id: 32,
    name: 'Semana 32 Embarazo',
    slug: 'semana-32-embarazo',
    week: '32',
    description: '',
    permalink: '/semana-32-embarazo/',
    link: 'https://eresmama.com/semana-32-del-embarazo/',
  },
  {
    id: 33,
    name: 'Semana 33 Embarazo',
    slug: 'semana-33-embarazo',
    week: '33',
    description: '',
    permalink: '/semana-33-embarazo/',
    link: 'https://eresmama.com/semana-33-del-embarazo/',
  },
  {
    id: 34,
    name: 'Semana 34 Embarazo',
    slug: 'semana-34-embarazo',
    week: '34',
    description: '',
    permalink: '/semana-34-embarazo/',
    link: 'https://eresmama.com/semana-34-del-embarazo/',
  },
  {
    id: 35,
    name: 'Semana 35 Embarazo',
    slug: 'semana-35-embarazo',
    week: '35',
    description: '',
    permalink: '/semana-35-embarazo/',
    link: 'https://eresmama.com/semana-35-del-embarazo/',
  },
  {
    id: 36,
    name: 'Semana 36 Embarazo',
    slug: 'semana-36-embarazo',
    week: '36',
    description: '',
    permalink: '/semana-36-embarazo/',
    link: 'https://eresmama.com/semana-36-del-embarazo/',
  },
  {
    id: 37,
    name: 'Semana 37 Embarazo',
    slug: 'semana-37-embarazo',
    week: '37',
    description: '',
    permalink: '/semana-37-embarazo/',
    link: 'https://eresmama.com/semana-37-del-embarazo/',
  },
  {
    id: 38,
    name: 'Semana 38 Embarazo',
    slug: 'semana-38-embarazo',
    week: '38',
    description: '',
    permalink: '/semana-38-embarazo/',
    link: 'https://eresmama.com/semana-38-del-embarazo/',
  },
  {
    id: 39,
    name: 'Semana 39 Embarazo',
    slug: 'semana-39-embarazo',
    week: '39',
    description: '',
    permalink: '/semana-39-embarazo/',
    link: 'https://eresmama.com/semana-39-del-embarazo/',
  },
  {
    id: 40,
    name: 'Semana 40 Embarazo',
    slug: 'semana-40-embarazo',
    week: '40',
    description: '',
    permalink: '/semana-40-embarazo/',
    link: 'https://eresmama.com/semana-40-del-embarazo/',
  }
];
