import {
  configBase, fontFamilies, spacings, fontSizes, sizes, shadows, customColors, commomColors, medias
} from '.';

export const themes = {
  a4a: {
    name: 'Android 4 All',
    base: 'a4a',
    configBase,
    fontFamilies,
    fontSizes,
    spacings,
    sizes,
    shadows,
    mainColor: 'lime',
    secondaryColor: 'grey-cold',
    customColors,
    commomColors,
    isColorizedMode: false,
    medias
  },
  buc: {
    name: 'Busco un Coche',
    base: 'buc',
    configBase,
    fontFamilies,
    fontSizes,
    spacings,
    sizes,
    shadows,
    mainColor: 'orange',
    secondaryColor: 'grey-cold',
    customColors,
    commomColors,
    isColorizedMode: true,
    headerColor: 'default',
    footerBaseColor: 'secondary',
    medias
  },
  ed: {
    name: 'Eres Deportista',
    base: 'ed',
    configBase,
    fontFamilies,
    fontSizes,
    spacings,
    sizes,
    shadows,
    mainColor: 'green',
    secondaryColor: 'acqua',
    customColors,
    commomColors,
    isColorizedMode: false,
    medias
  },
  em: {
    name: 'Eres Mamá',
    base: 'em',
    configBase,
    fontFamilies,
    fontSizes,
    spacings,
    sizes,
    shadows,
    mainColor: 'pink',
    secondaryColor: 'purple',
    customColors,
    commomColors,
    isColorizedMode: false,
    medias
  },
  lmem: {
    name: 'La Mente es Maravillosa',
    base: 'lmem',
    configBase,
    fontFamilies,
    fontSizes,
    spacings,
    sizes,
    shadows,
    mainColor: 'indigo',
    secondaryColor: 'acqua',
    customColors,
    commomColors,
    isColorizedMode: false,
    medias
  },
  ma: {
    name: 'Mis Animales',
    base: 'ma',
    configBase,
    fontFamilies,
    fontSizes,
    spacings,
    sizes,
    shadows,
    mainColor: 'red',
    secondaryColor: 'yellow',
    customColors,
    commomColors,
    isColorizedMode: false,
    medias
  },
  mcs: {
    name: 'Mejor con Salud',
    base: 'mcs',
    configBase,
    fontFamilies,
    fontSizes,
    spacings,
    sizes,
    shadows,
    mainColor: 'blue',
    secondaryColor: 'pink',
    customColors,
    commomColors,
    isColorizedMode: false,
    medias
  },
  md: {
    name: 'Mi Decoración',
    base: 'md',
    configBase,
    fontFamilies,
    fontSizes,
    spacings,
    sizes,
    shadows,
    mainColor: 'purple',
    secondaryColor: 'grey-warm',
    customColors,
    commomColors,
    isColorizedMode: false,
    medias
  },
  ms: {
    name: 'Muy Salud',
    base: 'ms',
    configBase,
    fontFamilies,
    fontSizes,
    spacings,
    sizes,
    shadows,
    mainColor: 'blue',
    secondaryColor: 'indigo',
    customColors,
    commomColors,
    isColorizedMode: false,
    medias
  },
  mv: {
    name: 'Mi Viaje',
    base: 'mv',
    configBase,
    fontFamilies,
    fontSizes,
    spacings,
    sizes,
    shadows,
    mainColor: 'red-candy',
    secondaryColor: 'yellow',
    customColors,
    commomColors,
    isColorizedMode: false,
    medias
  },
  uc: {
    name: 'Unycas',
    base: 'uc',
    configBase,
    fontFamilies,
    fontSizes,
    spacings,
    sizes,
    shadows,
    mainColor: 'grey-warm',
    secondaryColor: 'grey-cold',
    customColors,
    commomColors,
    isColorizedMode: false,
    medias
  },
  vbb: {
    name: 'Vuelos Baratos Baratos',
    base: 'vbb',
    configBase,
    fontFamilies,
    fontSizes,
    spacings,
    sizes,
    shadows,
    mainColor: 'blue-sky',
    secondaryColor: 'yellow',
    customColors,
    commomColors,
    isColorizedMode: false,
    medias
  },
  dol: {
    name: 'Dicas Online',
    base: 'dol',
    configBase,
    fontFamilies,
    fontSizes,
    spacings,
    sizes,
    shadows,
    mainColor: 'red',
    secondaryColor: 'grey-cold',
    customColors,
    commomColors,
    isColorizedMode: false,
    medias
  },
  ec: {
    name: 'eConsejos',
    base: 'ec',
    configBase,
    fontFamilies,
    fontSizes,
    spacings,
    sizes,
    shadows,
    mainColor: 'red',
    secondaryColor: 'grey-cold',
    customColors,
    commomColors,
    isColorizedMode: false,
    medias
  },
  epl: {
    name: 'El Placer de la Lectura',
    base: 'epl',
    configBase,
    fontFamilies,
    fontSizes,
    spacings,
    sizes,
    shadows,
    mainColor: 'orange-brownish',
    secondaryColor: 'grey-warm',
    customColors,
    commomColors,
    isColorizedMode: false,
    medias
  },
  ent: {
    name: 'Entrenamiento.com',
    base: 'ent',
    configBase,
    fontFamilies,
    fontSizes,
    spacings,
    sizes,
    shadows,
    mainColor: 'grey-warm',
    secondaryColor: 'orange',
    customColors,
    commomColors,
    isColorizedMode: true,
    headerColor: 'main.1000',
    footerBaseColor: 'main',
    medias
  },
  ds: {
    name: 'Deporte Saludable',
    base: 'ds',
    configBase,
    fontFamilies,
    fontSizes,
    spacings,
    sizes,
    shadows,
    mainColor: 'blue-azure',
    secondaryColor: 'grey-cold',
    customColors,
    commomColors,
    isColorizedMode: false,
    medias
  },
  eco: {
    name: 'Ecocosas',
    base: 'eco',
    configBase,
    fontFamilies,
    fontSizes,
    spacings,
    sizes,
    shadows,
    mainColor: 'green',
    secondaryColor: 'grey-cold',
    customColors,
    commomColors,
    isColorizedMode: false,
    medias
  },
  ces: {
    name: 'Cultura en Serie',
    base: 'ces',
    configBase,
    fontFamilies,
    fontSizes,
    spacings,
    sizes,
    shadows,
    mainColor: 'pink-reddish',
    secondaryColor: 'pink-reddish',
    customColors,
    commomColors,
    isColorizedMode: true,
    headerColor: 'main.500',
    footerBaseColor: 'main',
    medias
  }
};
