apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: {{ .Values.release.name }}-vs
  namespace: istio-system
  labels:
    name: {{ .Values.release.name }}-vs
spec:
  hosts:
    - {{ .Values.release.host }}
  gateways:
    - {{ .Values.istio.gateway }}
  http:
    - match:
        - uri:
            prefix: {{ .Values.release.prefix | default "/"}}
      route:
        - destination:
            host: {{ .Values.release.name }}.{{ .Values.release.namespace }}.svc.cluster.local
            port:
              number: {{ .Values.release.serverPort }}